# Generated by Django 4.2.30 on 2026-04-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='prfile_pic',
            new_name='profile_pic',
        ),
    ]
