# Generated by Django 4.2.30 on 2026-07-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_onlinepaymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepaymentrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='onlinepaymentrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_requests', to='ecomapp.order'),
        ),
        migrations.AlterField(
            model_name='onlinepaymentrequest',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], max_length=15, null=True),
        ),
        migrations.AlterModelTable(
            name='onlinepaymentrequest',
            table='online_payment_request',
        ),
    ]
