# Generated by Django 4.2.30 on 2026-07-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, help_text="Small tagline above title, e.g. 'New — The Quiet Collection'", max_length=100)),
                ('title', models.CharField(help_text='Main headline', max_length=200)),
                ('subtitle', models.TextField(blank=True, max_length=300)),
                ('banner_image', models.ImageField(upload_to='banners/')),
                ('primary_button_text', models.CharField(default='Shop Now', max_length=50)),
                ('primary_button_link', models.CharField(default='#featured', max_length=200)),
                ('secondary_button_text', models.CharField(blank=True, max_length=50)),
                ('secondary_button_link', models.CharField(blank=True, max_length=200)),
                ('badge_number', models.CharField(blank=True, help_text="e.g. '120+'", max_length=20)),
                ('badge_label', models.CharField(blank=True, help_text="e.g. 'Makers & small studios'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
