# Generated by Django 4.2.30 on 2026-07-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0013_herobanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herobanner',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='herobanner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Choto number age dekhabe (0,1,2...)'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='badge_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='badge_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
